export default {
  INVALID_RESTRICTION: "Técnico inexistente",
  INVALID_EMPTY_TEMPLATE: "Não foi possível criar o pedido. O template inserido está vazio.",
  INVALID_COLUMNS_SIZE: "Arquivo diferente do proposto no template ou preenchido incorretamente",
  INVALID_DATA: "Dados inválidos",
  RESTRICTED_TITLE: "Acesso negado",
  RESTRICTED_DESCRIPTION: "Seu perfil de usuário não possui acesso a esta funcionalidade.",
  RESTRICTED_BUTTON_TEXT: "Ir para tela inicial",
  APP_PANEL_SEND_DEFAULT_MESSAGE: "Preencher pelo menos um campo para realizar a busca",
  ORDER_CREATE_OK: "Pedido criado com sucesso",
  ORDER_CREATE_NOK: "Não foi possível criar o pedido",
  INVALID_REGISTRATION: "Matrícula inválida",
  ENGINEER_PSR: "Técnico fora da localidade ou PSR do solicitante.",
  ENGINEER_INATIVE: "Técnico inativo",
  INVALID_VALUE: "Valor inválido",
  REGISTRATION_NOT_FOUND: "Matrícula não informada",
  REGISTRATION_NOT_FOUND_REF: "Matrícula não encontrada nos dados de referência",
  FILE_NOT_FOUND: "Arquivo não encontrado",
  FILE_PURGED: "O arquivo utilizado no pedido não se encontra mais disponível para download",
  FILE_NON_EXISTENT: "O pedido selecionado não foi originado por importação de arquivo",
  DATE_RANGE_OVERLAP: "Conflito de datas para a mesma matrícula",
  TYPE_NOT_FOUND: "Não foi encontrado o tipo da solicitação.",
  INVALID_REASON: "Motivo de indisponibilidade inválido",
  REPEATED_REGISTRATION: "Matrícula em duplicidade",
  INVALID_LENGTH: "Tamanho inválido",
  FIELD_REQUIRED: "Campo obrigatório",
  FIELD: "Coluna",
  TAB: "Aba",
  LINE: "linha",
  WITH_ERROR: "com erro",
  FROM_FILE: "do arquivo",
  INVALID_PARAMS: "Dados inválidos",
  INVALID_DATA_ADCC: "Dados inválidos enviados para serviço",
  INVALID_CRITERIA: "Dados dos critérios inválidos",
  INVALID_REQUEST: "Requisição ao serviço inválida",
  RULE_NOT_FOUND: "Regra de Comunicação não encontrada",
  MESSAGE_DELETE_RULE_ASSOCIATED_NOK:
    "Não é possível excluir um modelo de mensagem associado a uma ou mais Regra(s) de Comunicação. Este modelo está associado as regras: ",
  INVALID_DATE_RANGE: "Data(s) de início e/ou final inválida(s).",
  INVALID_DATE_FORMAT: "Formato da(s) data(s) de início e/ou final inválida(s).",
  INVALID_TABLE_NAME: "Nome da tabela inválido",
  INVALID_FIELD_TYPE: "Tipo de dado inválido",
  INVALID_CARACTER: "Caracter inválido",
  INVALID_FILE_RECORD: "Os dados do arquivo são inválidos.",
  INVALID_FIELD_LENGTH: "Número de caracteres inválido",
  INVALID_FIELD_FIXED_LENGTH: "Número de caracteres deve ser exatamente o solicitado",
  INVALID_FIELD_REQUIRED: "Dado obrigatório inválido",
  INVALID_COLUMNS_REQUIRED: "Coluna obrigatória não fornecida",
  INVALID_FIELD_OPTION: "Não é uma opção permitida",
  INVALID_FIELD_REF: "Opção não encontrada nos dados de referência",
  DUPLICATED_REF_NAME: "Já existe outro registro cadastrado neste Dicionário com o mesmo NAME",
  INVALID_FIELD_PARENT_REF: "Opção não encontrada nos dados pai de referência",
  INVALID_FIELD_CHILD_REF: "Opção não encontrada nos dados filhos de referência",
  INVALID_FIELD_NOT_UNIQUE: "Os dados dessa coluna não podem ser repetidos",
  INVALID_FIELD_NOT_FIXED: "O dado dessa coluna deve ser o mesmo em todas as linhas",
  INVALID_SCHEDULE_DATE: 'Campo "ScheduleDate" inválido. Data precisa ser igual à hoje.',
  INVALID_ENGINEER_WORKZONE: "Área(s) de trabalho fora da área de atuação do técnico:",
  WORKZONE_NOT_FOUND: "Área(s) de trabalho não encontradas nos dados de referência",
  PROCESSING_JOB_ERROR: "Não foi possível processar alguns itens deste pedido, mesmo após várias tentativas",
  PROCESSING_ITEM_ERROR: "Não foi possível enviar este item para o Click por indisponibilidade do SOA",
  PROCESSING_ITEM_ERROR_CLICK: "Não foi possível enviar este item por indisponibilidade do serviço do Click",
  ORDER_EXTRACT_PROCESSING:
    "Seu pedido de extração está em processamento. O arquivo estará disponível para download no link abaixo, após o término do processamento.",
  ORDER_EXTRACT_PROCESSING_ERROR:
    "Houve um erro durante o processamento deste pedido. Por favor, tente fazer a extração dos dados novamente.",
  DATA_VALIDATE_ERROR: "Erro na validação dos dados.",
  PROFILE_VALIDATE_ERROR: "Os dados enviados são inválidos",
  ERROR_ON_SEND: "Erro ao tentar enviar este item para a fila de processamento",
  ITEM_JMS_SERVICE_ERROR: "Serviço indisponível durante o processamento deste item",
  JMS_SERVICE_ERROR: "Serviço de fila de processamento indisponível",
  WSDL_NOT_FOUND: "Serviço de integração indisponível ou não encontrado",
  SERVICE_COMM_ERROR:
    "Para realizar essa operação são necessárias comunicações com serviços externos que neste momento podem estar indisponíveis.",
  JMS_TIME_OUT_ERROR: "Não houve retorno do Click",
  "Error: Route not found": "A API não existe(Route not found)",
};
